### ISSUE TITLE
wildcard issue when reading files

### ISSUE THREAD

**Issue by faicalsaid** [globalmentor/hadoop-bare-naked-local-fs#1]
Hello,

Happy to see that you managed to get rid of winutils. That's really a great news.

I have an issue while reading folders of csv files. my path contains a wild card and this seems to be creating some issues:
```
Caused by: java.nio.file.InvalidPathException: Illegal char <*> at index 50: C:\Code\blabla\*.csv
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.io.File.toPath(File.java:2236)
	at com.globalmentor.apache.hadoop.fs.NakedLocalFileSystem.toNioPath(NakedLocalFileSystem.java:84)
	at com.globalmentor.apache.hadoop.fs.NakedLocalFileSystem.getFileStatus(NakedLocalFileSystem.java:225)
	at org.apache.hadoop.fs.FilterFileSystem.getFileStatus(FilterFileSystem.java:454)
	at org.apache.hadoop.fs.FileSystem.isDirectory(FileSystem.java:1700)
	at org.apache.spark.sql.execution.streaming.FileStreamSink$.hasMetadata(FileStreamSink.scala:47)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:377)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:325)
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$3(DataFrameReader.scala:307)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:307)
	at org.apache.spark.sql.DataFrameReader.csv(DataFrameReader.scala:795)
	at org.apache.spark.sql.DataFrameReader.csv(DataFrameReader.scala:595)
```
With winutils this was working correctly. I think there is a need to add some implementation to allow switch from winutils.

Thanks.

Faical

**Comment by garretwilson** [comment]
Interesting. Thanks for reporting this. Off the top of my head I'll bet the original implementation was playing loose with the rules to have an invalid path represent a wildcard match.

Could you do me a favor and give me some sort of high-level code you would expect to work with this? The stack trace is helpful, thanks. When I look into it I can probably make a lot of guesses just from that. But I'll need to reproduce it and write a unit test. Could you describe what you were doing and provide any sort of sample code, even a pseudocode outline, that might trigger this?

**Comment by garretwilson** [comment]
@faicalsaid , just in case you missed my earlier message (see above), can you give me a snippet of high-level code you are using with this?

**Comment by garretwilson** [comment]
@faicalsaid , just pinging you again to see if you see if you can give me a bit of the high-level code that resulted in this exception. Thanks.

**Comment by garretwilson** [comment]
> … my path contains a wild card …

I'm suspicious of this ticket, because I don't understand what you mean when you say "contains a wild card". Windows [forbids the use of a wildcard](https://en.wikipedia.org/wiki/Filename#In_Windows) in a path. Does your filename actually contain an asterisk? I imagine not. I imagine (inferring from the stack track) that you are asking Spark somehow to pull in files, and using `*` as a wildcard.

I see that one place in the stack track that eventually calls `NakedLocalFileSystem` is `org.apache.hadoop.fs.FileSystem.isDirectory(FileSystem.java:1700)`. (Note that `FileSystem.isDirectory()` is currently deprecated, but that may be out of your control.) I'm guessing that in `NakedLocalFileSystem` I could override `isDirectory()` and catch the `java.nio.file.InvalidPathException`, and simply return `false`, in essence saying that `C:\Code\blabla\*.csv` is not a directory (and can't be, because it's an invalid path).

But then how would I verify that it worked, since I don't have a reproducible case, and I can't get in touch with the person who filed the ticket to begin with?

Furthermore, it seems odd that Spark would be doing some glob operation and check to see if the _globbed path itself_ is a directory. Maybe that's some inevitable way this is cobbled together with Spark and Hadoop (which wouldn't surprise me), but I really hate to then cobble some fix on top of something I don't even know what's happening.

I believe this sort of thing is something I can address, but I really need more information from you about how this is being called so that I can at least provide some sort of test for it. I hope to hear back from you, or from someone else with the same problem. Otherwise I'll have to close the ticket.
